--- 
haproxy: 
  download_url: http://haproxy.1wt.eu/download/1.4/src/haproxy-1.4.15.tar.gz
  config: 
    global:
      daemon:
      maxconn: 8
      # log: /Users/kburton/personal/projects/sandbox/rabbitmq/haproxy.log user
      pidfile: pid.haproxy
    defaults:
      retries: 3
      contimeout: 5000
      clitimeout: 2d
      srvtimeout: 2d
    nodes: 
    - listen: "amqp01 127.0.0.1:25671"
      mode:    tcp
      balance: roundrobin
      option:  tcpka
      server:  rabbit01 127.0.0.1:15671
    - listen:    amqp02 127.0.0.1:25672
      mode:    tcp
      balance: roundrobin
      option:  tcpka
      server:  rabbit02 127.0.0.1:15672
